collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single

head_scripts:
  - /assets/css/custom.css

remote_theme: "mmistakes/minimal-mistakes"

custom_css:
  - /assets/css/custom.css
