collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

custom_css:
  - /assets/css/custom.css
